### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by ghost** [maximummeteor/server-transform#5]
Hello Max,

Just want to say thank you so much for making this package... after about 5 hours of trying to do somthing I found this package... And can now do it in 5 lines of code!  You are a hero!  Thank you so much.

**Comment by maxnowack** [comment]
You're welcome :)
If you run into performance issues using this package, [try this one](https://github.com/maximummeteor/computed-fields)

**Comment by ghost** [comment]
Hi Max,

Why would I run into performance issues using this one, but not the other?

**Comment by maxnowack** [comment]
The serverside transformation will be executed every time a user subscribe to a `publishTransformed` publication. Depending on the complexity of the transformation, this can raise up your server load.

I've developed this package because I needed some complex reactive aggregations for each document in a collection. But the aggregations had too much impact on the CPU load. So I decided to find another way to do this and developed the `maximum:computed-fields` package.
Maybe your case is similar.

Also see #4
